# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('starting_value', models.IntegerField(default=0)),
                ('target_value', models.IntegerField(default=100)),
                ('current_value', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[(b'1', b'In Progress'), (b'2', b'Failed'), (b'3', b'Achieved')], max_length=1)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='goal',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='keyresult',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.Objective'),
        ),
    ]
