# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20161006_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='progress',
        ),
    ]
