# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-17 17:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('starting_value', models.FloatField(default=0)),
                ('target_value', models.FloatField(default=100)),
                ('current_value', models.FloatField(default=0)),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='goals.Goal')),
            ],
        ),
    ]
