# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='objective',
            new_name='goal',
        ),
    ]
