# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_auto_20161007_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyresult',
            name='current_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='starting_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='target_value',
            field=models.FloatField(default=100),
        ),
    ]
